import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import StyledComponentsRegistry from "@/lib/styled-components-registry";
import "./globals.css";

const barlow = Barlow({
  variable: "--font-barlow",
  subsets: ['latin'],
  weight: ['100', '400', '700']
});

export const metadata: Metadata = {
  title: "Live Scoring App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} antialiased`}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
